#!/usr/bin/env bash
set -euo pipefail


PROBLEM_ID="8.4.S2"


BASE_DIR="c/.tls"
WORKING_DIR="${BASE_DIR}/problems/${PROBLEM_ID}"
rm -rf ~/"${WORKING_DIR}"
mkdir -p ~/"${WORKING_DIR}"
CASE_NUMBER=0


CASE_NUMBER=$((${CASE_NUMBER} + 1))
JUDGE_DIR="${WORKING_DIR}/judge/${CASE_NUMBER}"
mkdir -p ~/"${JUDGE_DIR}"
cat << "EOF" > ~/"${JUDGE_DIR}/input.txt"
0
EOF
cat << "EOF" > ~/"${JUDGE_DIR}/expected-output.txt"
---
333
---
X
', (code)=>code, (result)=>{return result.trimEnd().match(
EOF
cat << "EOF" > ~/"${JUDGE_DIR}/transform.js"
"use strict";
const transform = (code) => {return code;};
const fs = require('fs');
if (process.argv.length < 2) { process.exit(1); }
const codeFilename = process.argv[2];
const transformed = transform(fs.readFileSync(codeFilename, "utf8"));
process.stdout.write(transformed);
EOF
cat << "EOF" > ~/"${JUDGE_DIR}/verify.js"
"use strict";
const verify = (output) => {return output.trimEnd().match(/---\s+X\s*$/);};
const fs = require('fs');
const result = verify(fs.readFileSync("output.txt", "utf8"));
if (result) {
    process.stdout.write("1\n");
} else {
    process.stdout.write("0\n");
}
EOF


CASE_NUMBER=$((${CASE_NUMBER} + 1))
JUDGE_DIR="${WORKING_DIR}/judge/${CASE_NUMBER}"
mkdir -p ~/"${JUDGE_DIR}"
cat << "EOF" > ~/"${JUDGE_DIR}/input.txt"
1
EOF
cat << "EOF" > ~/"${JUDGE_DIR}/expected-output.txt"
---
XXX
X X
XXX
EOF
cat << "EOF" > ~/"${JUDGE_DIR}/transform.js"
"use strict";
const transform = (code) => {return code;};
const fs = require('fs');
if (process.argv.length < 2) { process.exit(1); }
const codeFilename = process.argv[2];
const transformed = transform(fs.readFileSync(codeFilename, "utf8"));
process.stdout.write(transformed);
EOF
cat << "EOF" > ~/"${JUDGE_DIR}/verify.js"
"use strict";
const verify = (output) => {return output.trimEnd().match(/---\s+XXX\nX X\nXXX\s*$/);};
const fs = require('fs');
const result = verify(fs.readFileSync("output.txt", "utf8"));
if (result) {
    process.stdout.write("1\n");
} else {
    process.stdout.write("0\n");
}
EOF


CASE_NUMBER=$((${CASE_NUMBER} + 1))
JUDGE_DIR="${WORKING_DIR}/judge/${CASE_NUMBER}"
mkdir -p ~/"${JUDGE_DIR}"
cat << "EOF" > ~/"${JUDGE_DIR}/input.txt"
2
EOF
cat << "EOF" > ~/"${JUDGE_DIR}/expected-output.txt"
---
XXXXXXXXX
X XX XX X
XXXXXXXXX
XXX   XXX
X X   X X
XXX   XXX
XXXXXXXXX
X XX XX X
XXXXXXXXX
EOF
cat << "EOF" > ~/"${JUDGE_DIR}/transform.js"
"use strict";
const transform = (code) => {return code;};
const fs = require('fs');
if (process.argv.length < 2) { process.exit(1); }
const codeFilename = process.argv[2];
const transformed = transform(fs.readFileSync(codeFilename, "utf8"));
process.stdout.write(transformed);
EOF
cat << "EOF" > ~/"${JUDGE_DIR}/verify.js"
"use strict";
const verify = (output) => {return output.trimEnd().match(/---\s+XXXXXXXXX\nX XX XX X\nXXXXXXXXX\nXXX   XXX\nX X   X X\nXXX   XXX\nXXXXXXXXX\nX XX XX X\nXXXXXXXXX\s*$/);};
const fs = require('fs');
const result = verify(fs.readFileSync("output.txt", "utf8"));
if (result) {
    process.stdout.write("1\n");
} else {
    process.stdout.write("0\n");
}
EOF


CASE_NUMBER=$((${CASE_NUMBER} + 1))
JUDGE_DIR="${WORKING_DIR}/judge/${CASE_NUMBER}"
mkdir -p ~/"${JUDGE_DIR}"
cat << "EOF" > ~/"${JUDGE_DIR}/input.txt"
3
EOF
cat << "EOF" > ~/"${JUDGE_DIR}/expected-output.txt"
---
XXXXXXXXXXXXXXXXXXXXXXXXXXX
X XX XX XX XX XX XX XX XX X
XXXXXXXXXXXXXXXXXXXXXXXXXXX
XXX   XXXXXX   XXXXXX   XXX
X X   X XX X   X XX X   X X
XXX   XXXXXX   XXXXXX   XXX
XXXXXXXXXXXXXXXXXXXXXXXXXXX
X XX XX XX XX XX XX XX XX X
XXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXX         XXXXXXXXX
X XX XX X         X XX XX X
XXXXXXXXX         XXXXXXXXX
XXX   XXX         XXX   XXX
X X   X X         X X   X X
XXX   XXX         XXX   XXX
XXXXXXXXX         XXXXXXXXX
X XX XX X         X XX XX X
XXXXXXXXX         XXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXX
X XX XX XX XX XX XX XX XX X
XXXXXXXXXXXXXXXXXXXXXXXXXXX
XXX   XXXXXX   XXXXXX   XXX
X X   X XX X   X XX X   X X
XXX   XXXXXX   XXXXXX   XXX
XXXXXXXXXXXXXXXXXXXXXXXXXXX
X XX XX XX XX XX XX XX XX X
XXXXXXXXXXXXXXXXXXXXXXXXXXX
EOF
cat << "EOF" > ~/"${JUDGE_DIR}/transform.js"
"use strict";
const transform = (code) => {return code;};
const fs = require('fs');
if (process.argv.length < 2) { process.exit(1); }
const codeFilename = process.argv[2];
const transformed = transform(fs.readFileSync(codeFilename, "utf8"));
process.stdout.write(transformed);
EOF
cat << "EOF" > ~/"${JUDGE_DIR}/verify.js"
"use strict";
const verify = (output) => {return output.trimEnd().match(/---\s+XXXXXXXXXXXXXXXXXXXXXXXXXXX\nX XX XX XX XX XX XX XX XX X\nXXXXXXXXXXXXXXXXXXXXXXXXXXX\nXXX   XXXXXX   XXXXXX   XXX\nX X   X XX X   X XX X   X X\nXXX   XXXXXX   XXXXXX   XXX\nXXXXXXXXXXXXXXXXXXXXXXXXXXX\nX XX XX XX XX XX XX XX XX X\nXXXXXXXXXXXXXXXXXXXXXXXXXXX\nXXXXXXXXX         XXXXXXXXX\nX XX XX X         X XX XX X\nXXXXXXXXX         XXXXXXXXX\nXXX   XXX         XXX   XXX\nX X   X X         X X   X X\nXXX   XXX         XXX   XXX\nXXXXXXXXX         XXXXXXXXX\nX XX XX X         X XX XX X\nXXXXXXXXX         XXXXXXXXX\nXXXXXXXXXXXXXXXXXXXXXXXXXXX\nX XX XX XX XX XX XX XX XX X\nXXXXXXXXXXXXXXXXXXXXXXXXXXX\nXXX   XXXXXX   XXXXXX   XXX\nX X   X XX X   X XX X   X X\nXXX   XXXXXX   XXXXXX   XXX\nXXXXXXXXXXXXXXXXXXXXXXXXXXX\nX XX XX XX XX XX XX XX XX X\nXXXXXXXXXXXXXXXXXXXXXXXXXXX\s*$/);};
const fs = require('fs');
const result = verify(fs.readFileSync("output.txt", "utf8"));
if (result) {
    process.stdout.write("1\n");
} else {
    process.stdout.write("0\n");
}
EOF


CASE_NUMBER=$((${CASE_NUMBER} + 1))
JUDGE_DIR="${WORKING_DIR}/judge/${CASE_NUMBER}"
mkdir -p ~/"${JUDGE_DIR}"
cat << "EOF" > ~/"${JUDGE_DIR}/input.txt"
4
EOF
cat << "EOF" > ~/"${JUDGE_DIR}/expected-output.txt"
---
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
X XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX X
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXX
X X   X XX X   X XX X   X XX X   X XX X   X XX X   X XX X   X XX X   X XX X   X X
XXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
X XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX X
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXX         XXXXXXXXXXXXXXXXXX         XXXXXXXXXXXXXXXXXX         XXXXXXXXX
X XX XX X         X XX XX XX XX XX X         X XX XX XX XX XX X         X XX XX X
XXXXXXXXX         XXXXXXXXXXXXXXXXXX         XXXXXXXXXXXXXXXXXX         XXXXXXXXX
XXX   XXX         XXX   XXXXXX   XXX         XXX   XXXXXX   XXX         XXX   XXX
X X   X X         X X   X XX X   X X         X X   X XX X   X X         X X   X X
XXX   XXX         XXX   XXXXXX   XXX         XXX   XXXXXX   XXX         XXX   XXX
XXXXXXXXX         XXXXXXXXXXXXXXXXXX         XXXXXXXXXXXXXXXXXX         XXXXXXXXX
X XX XX X         X XX XX XX XX XX X         X XX XX XX XX XX X         X XX XX X
XXXXXXXXX         XXXXXXXXXXXXXXXXXX         XXXXXXXXXXXXXXXXXX         XXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
X XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX X
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXX
X X   X XX X   X XX X   X XX X   X XX X   X XX X   X XX X   X XX X   X XX X   X X
XXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
X XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX X
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXX                           XXXXXXXXXXXXXXXXXXXXXXXXXXX
X XX XX XX XX XX XX XX XX X                           X XX XX XX XX XX XX XX XX X
XXXXXXXXXXXXXXXXXXXXXXXXXXX                           XXXXXXXXXXXXXXXXXXXXXXXXXXX
XXX   XXXXXX   XXXXXX   XXX                           XXX   XXXXXX   XXXXXX   XXX
X X   X XX X   X XX X   X X                           X X   X XX X   X XX X   X X
XXX   XXXXXX   XXXXXX   XXX                           XXX   XXXXXX   XXXXXX   XXX
XXXXXXXXXXXXXXXXXXXXXXXXXXX                           XXXXXXXXXXXXXXXXXXXXXXXXXXX
X XX XX XX XX XX XX XX XX X                           X XX XX XX XX XX XX XX XX X
XXXXXXXXXXXXXXXXXXXXXXXXXXX                           XXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXX         XXXXXXXXX                           XXXXXXXXX         XXXXXXXXX
X XX XX X         X XX XX X                           X XX XX X         X XX XX X
XXXXXXXXX         XXXXXXXXX                           XXXXXXXXX         XXXXXXXXX
XXX   XXX         XXX   XXX                           XXX   XXX         XXX   XXX
X X   X X         X X   X X                           X X   X X         X X   X X
XXX   XXX         XXX   XXX                           XXX   XXX         XXX   XXX
XXXXXXXXX         XXXXXXXXX                           XXXXXXXXX         XXXXXXXXX
X XX XX X         X XX XX X                           X XX XX X         X XX XX X
XXXXXXXXX         XXXXXXXXX                           XXXXXXXXX         XXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXX                           XXXXXXXXXXXXXXXXXXXXXXXXXXX
X XX XX XX XX XX XX XX XX X                           X XX XX XX XX XX XX XX XX X
XXXXXXXXXXXXXXXXXXXXXXXXXXX                           XXXXXXXXXXXXXXXXXXXXXXXXXXX
XXX   XXXXXX   XXXXXX   XXX                           XXX   XXXXXX   XXXXXX   XXX
X X   X XX X   X XX X   X X                           X X   X XX X   X XX X   X X
XXX   XXXXXX   XXXXXX   XXX                           XXX   XXXXXX   XXXXXX   XXX
XXXXXXXXXXXXXXXXXXXXXXXXXXX                           XXXXXXXXXXXXXXXXXXXXXXXXXXX
X XX XX XX XX XX XX XX XX X                           X XX XX XX XX XX XX XX XX X
XXXXXXXXXXXXXXXXXXXXXXXXXXX                           XXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
X XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX X
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXX
X X   X XX X   X XX X   X XX X   X XX X   X XX X   X XX X   X XX X   X XX X   X X
XXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
X XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX X
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXX         XXXXXXXXXXXXXXXXXX         XXXXXXXXXXXXXXXXXX         XXXXXXXXX
X XX XX X         X XX XX XX XX XX X         X XX XX XX XX XX X         X XX XX X
XXXXXXXXX         XXXXXXXXXXXXXXXXXX         XXXXXXXXXXXXXXXXXX         XXXXXXXXX
XXX   XXX         XXX   XXXXXX   XXX         XXX   XXXXXX   XXX         XXX   XXX
X X   X X         X X   X XX X   X X         X X   X XX X   X X         X X   X X
XXX   XXX         XXX   XXXXXX   XXX         XXX   XXXXXX   XXX         XXX   XXX
XXXXXXXXX         XXXXXXXXXXXXXXXXXX         XXXXXXXXXXXXXXXXXX         XXXXXXXXX
X XX XX X         X XX XX XX XX XX X         X XX XX XX XX XX X         X XX XX X
XXXXXXXXX         XXXXXXXXXXXXXXXXXX         XXXXXXXXXXXXXXXXXX         XXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
X XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX X
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXX
X X   X XX X   X XX X   X XX X   X XX X   X XX X   X XX X   X XX X   X XX X   X X
XXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
X XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX X
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
EOF
cat << "EOF" > ~/"${JUDGE_DIR}/transform.js"
"use strict";
const transform = (code) => {return code;};
const fs = require('fs');
if (process.argv.length < 2) { process.exit(1); }
const codeFilename = process.argv[2];
const transformed = transform(fs.readFileSync(codeFilename, "utf8"));
process.stdout.write(transformed);
EOF
cat << "EOF" > ~/"${JUDGE_DIR}/verify.js"
"use strict";
const verify = (output) => {return output.trimEnd().match(/---\s+XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\nX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX X\nXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\nXXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXX\nX X   X XX X   X XX X   X XX X   X XX X   X XX X   X XX X   X XX X   X XX X   X X\nXXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXX\nXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\nX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX X\nXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\nXXXXXXXXX         XXXXXXXXXXXXXXXXXX         XXXXXXXXXXXXXXXXXX         XXXXXXXXX\nX XX XX X         X XX XX XX XX XX X         X XX XX XX XX XX X         X XX XX X\nXXXXXXXXX         XXXXXXXXXXXXXXXXXX         XXXXXXXXXXXXXXXXXX         XXXXXXXXX\nXXX   XXX         XXX   XXXXXX   XXX         XXX   XXXXXX   XXX         XXX   XXX\nX X   X X         X X   X XX X   X X         X X   X XX X   X X         X X   X X\nXXX   XXX         XXX   XXXXXX   XXX         XXX   XXXXXX   XXX         XXX   XXX\nXXXXXXXXX         XXXXXXXXXXXXXXXXXX         XXXXXXXXXXXXXXXXXX         XXXXXXXXX\nX XX XX X         X XX XX XX XX XX X         X XX XX XX XX XX X         X XX XX X\nXXXXXXXXX         XXXXXXXXXXXXXXXXXX         XXXXXXXXXXXXXXXXXX         XXXXXXXXX\nXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\nX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX X\nXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\nXXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXX\nX X   X XX X   X XX X   X XX X   X XX X   X XX X   X XX X   X XX X   X XX X   X X\nXXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXX\nXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\nX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX X\nXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\nXXXXXXXXXXXXXXXXXXXXXXXXXXX                           XXXXXXXXXXXXXXXXXXXXXXXXXXX\nX XX XX XX XX XX XX XX XX X                           X XX XX XX XX XX XX XX XX X\nXXXXXXXXXXXXXXXXXXXXXXXXXXX                           XXXXXXXXXXXXXXXXXXXXXXXXXXX\nXXX   XXXXXX   XXXXXX   XXX                           XXX   XXXXXX   XXXXXX   XXX\nX X   X XX X   X XX X   X X                           X X   X XX X   X XX X   X X\nXXX   XXXXXX   XXXXXX   XXX                           XXX   XXXXXX   XXXXXX   XXX\nXXXXXXXXXXXXXXXXXXXXXXXXXXX                           XXXXXXXXXXXXXXXXXXXXXXXXXXX\nX XX XX XX XX XX XX XX XX X                           X XX XX XX XX XX XX XX XX X\nXXXXXXXXXXXXXXXXXXXXXXXXXXX                           XXXXXXXXXXXXXXXXXXXXXXXXXXX\nXXXXXXXXX         XXXXXXXXX                           XXXXXXXXX         XXXXXXXXX\nX XX XX X         X XX XX X                           X XX XX X         X XX XX X\nXXXXXXXXX         XXXXXXXXX                           XXXXXXXXX         XXXXXXXXX\nXXX   XXX         XXX   XXX                           XXX   XXX         XXX   XXX\nX X   X X         X X   X X                           X X   X X         X X   X X\nXXX   XXX         XXX   XXX                           XXX   XXX         XXX   XXX\nXXXXXXXXX         XXXXXXXXX                           XXXXXXXXX         XXXXXXXXX\nX XX XX X         X XX XX X                           X XX XX X         X XX XX X\nXXXXXXXXX         XXXXXXXXX                           XXXXXXXXX         XXXXXXXXX\nXXXXXXXXXXXXXXXXXXXXXXXXXXX                           XXXXXXXXXXXXXXXXXXXXXXXXXXX\nX XX XX XX XX XX XX XX XX X                           X XX XX XX XX XX XX XX XX X\nXXXXXXXXXXXXXXXXXXXXXXXXXXX                           XXXXXXXXXXXXXXXXXXXXXXXXXXX\nXXX   XXXXXX   XXXXXX   XXX                           XXX   XXXXXX   XXXXXX   XXX\nX X   X XX X   X XX X   X X                           X X   X XX X   X XX X   X X\nXXX   XXXXXX   XXXXXX   XXX                           XXX   XXXXXX   XXXXXX   XXX\nXXXXXXXXXXXXXXXXXXXXXXXXXXX                           XXXXXXXXXXXXXXXXXXXXXXXXXXX\nX XX XX XX XX XX XX XX XX X                           X XX XX XX XX XX XX XX XX X\nXXXXXXXXXXXXXXXXXXXXXXXXXXX                           XXXXXXXXXXXXXXXXXXXXXXXXXXX\nXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\nX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX X\nXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\nXXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXX\nX X   X XX X   X XX X   X XX X   X XX X   X XX X   X XX X   X XX X   X XX X   X X\nXXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXX\nXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\nX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX X\nXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\nXXXXXXXXX         XXXXXXXXXXXXXXXXXX         XXXXXXXXXXXXXXXXXX         XXXXXXXXX\nX XX XX X         X XX XX XX XX XX X         X XX XX XX XX XX X         X XX XX X\nXXXXXXXXX         XXXXXXXXXXXXXXXXXX         XXXXXXXXXXXXXXXXXX         XXXXXXXXX\nXXX   XXX         XXX   XXXXXX   XXX         XXX   XXXXXX   XXX         XXX   XXX\nX X   X X         X X   X XX X   X X         X X   X XX X   X X         X X   X X\nXXX   XXX         XXX   XXXXXX   XXX         XXX   XXXXXX   XXX         XXX   XXX\nXXXXXXXXX         XXXXXXXXXXXXXXXXXX         XXXXXXXXXXXXXXXXXX         XXXXXXXXX\nX XX XX X         X XX XX XX XX XX X         X XX XX XX XX XX X         X XX XX X\nXXXXXXXXX         XXXXXXXXXXXXXXXXXX         XXXXXXXXXXXXXXXXXX         XXXXXXXXX\nXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\nX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX X\nXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\nXXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXX\nX X   X XX X   X XX X   X XX X   X XX X   X XX X   X XX X   X XX X   X XX X   X X\nXXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXXXXX   XXX\nXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\nX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX X\nXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\s*$/);};
const fs = require('fs');
const result = verify(fs.readFileSync("output.txt", "utf8"));
if (result) {
    process.stdout.write("1\n");
} else {
    process.stdout.write("0\n");
}
EOF
